basePath: /v1
host: api.engin.app
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /signup:
    post:
      consumes:
      - application/json
      description: Validates and signes a user up to the system
      parameters:
      - in: query
        name: account_name
        type: string
      - in: query
        name: email
        required: true
        type: string
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: passwordconfirm
        required: true
        type: string
      - in: query
        name: temp
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Creates an account
      tags:
      - signup
swagger: "2.0"
